export const socialForm = [
    {
        name: 'twitter',
        link: 'https://twitter.com/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/twitter.svg',
        shields: 'https://img.shields.io/badge/twitter-x?style=for-the-badge&logo=x&logoColor=white&color=%230f1419',
        placeholder: 'twitter username',
    },
    {
        name: 'dev.to',
        link: 'https://dev.to/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/dev-dot-to.svg',
        shields: 'https://img.shields.io/badge/dev-to?style=for-the-badge&logo=dev-to&logoColor=white&color=black',
        placeholder: 'dev.to username',
    },
    {
        name: 'linkedin',
        link: 'https://www.linkedin.com/in/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg',
        shields: 'https://img.shields.io/badge/linkedin-logo?style=for-the-badge&logo=linkedin&logoColor=white&color=%230a77b6',
        placeholder: 'linkedin username',
    },
    {
        name: 'facebook',
        link: 'https://www.facebook.com/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/facebook.svg',
        shields: 'https://img.shields.io/badge/facebook-logo?style=for-the-badge&logo=facebook&logoColor=white&color=%230866ff',
        placeholder: 'facebook username',
    },
    {
        name: 'instagram',
        link: 'https://www.instagram.com/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/instagram.svg',
        shields: 'https://img.shields.io/badge/instagram-logo?style=for-the-badge&logo=instagram&logoColor=white&color=%23F35369',
        placeholder: 'instagram username',
    },
    {
        name: 'codepen',
        link: 'https://www.codepen.io/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/codepen.svg',
        shields: 'https://img.shields.io/badge/codepen?style=for-the-badge&logo=codepen&logoColor=white&color=black',
        placeholder: 'codepen username',
    },
    {
        name: 'codesandbox',
        link: 'https://codesandbox.com/u/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/codesandbox.svg',
        shields: 'https://img.shields.io/badge/codesandbox?style=for-the-badge&logo=codesandbox&logoColor=white&color=black',
        placeholder: 'codesandbox username',
    },
    {
        name: 'dribbble',
        link: 'https://www.dribbble.com/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dribbble.svg',
        shields: 'https://img.shields.io/badge/dribbble-logo?style=for-the-badge&logo=dribbble&logoColor=white&color=%23ea64d9',
        placeholder: 'dribbble username',
    },
    {
        name: 'behance',
        link: 'https://www.behance.net/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/behance.svg',
        shields: 'https://img.shields.io/badge/behance-logo?style=for-the-badge&logo=behance&logoColor=white&color=%230057ff',
        placeholder: 'behance username',
    },
    {
        name: 'medium',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/medium.svg',
        shields: 'https://img.shields.io/badge/medium-logo?style=for-the-badge&logo=medium&logoColor=white&color=black',
        placeholder: 'medium username (with @)',
    },
    {
        name: 'youtube',
        link: 'https://www.youtube.com/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/youtube.svg',
        shields: 'https://img.shields.io/badge/youtube-logo?style=for-the-badge&logo=youtube&logoColor=white&color=%23cc0000',
        placeholder: 'youtube channel name (with @)',
    },
    {
        name: 'stackoverflow',
        link: 'https://stackoverflow.com/users/',
        icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/stackoverflow.svg',
        shields: 'https://img.shields.io/badge/stackoverflow-logo?style=for-the-badge&logo=stackoverflow&logoColor=white&color=%23cc0000',
        placeholder: 'stackoverflow user ID',
    }
]